services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: shopping_cart
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  localstack:
    image: localstack/localstack:latest
    environment:
      - SERVICES=dynamodb
    ports:
      - "4566:4566"
    volumes:
      - localstack_data:/var/lib/localstack
      -
  redis:
    image: redis:8
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  localstack_data:
